services:
    BorysZielonka\ApiStoreProductBundle\Service\ProductService:
        class: BorysZielonka\ApiStoreProductBundle\Service\ProductService
        arguments: ["@doctrine.orm.entity_manager"]
