<?php
namespace BorysZielonka\ApiStoreProductBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function getProductListByMoreThanAmount($MoreThanAmount)
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->select('p, p.id, p.name, p.amount');
        $queryBuilder->where('p.amount > :amount');
        $queryBuilder->setParameter('amount', $MoreThanAmount);

        return $queryBuilder->getQuery()->getResult();
    }

    public function getProductListByAvailability($inStock)
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->select('p.id, p.name, p.amount');
        if ($inStock) {
            error_log('niesuper');
            $queryBuilder->where('p.amount >= 1');
        } else {
            error_log('super');
            $queryBuilder->where('p.amount = 0');
        }
        
        return $queryBuilder->getQuery()->getResult();
    }
}
